"""Full report renderer — every finding grouped by priority band.

Shows complete detail: all findings with file path, line, CWE, severity,
confidence breakdown, and remediation context. Grouped by URGENT, ELEVATED,
MODERATE, LOW with per-band counts.
"""
from __future__ import annotations

from security_review import __version__
from security_review.reporting.common import ReportData, render_degradations_md, triage_status


def render_full(data: ReportData) -> str:
    """Render a complete markdown report with every finding."""
    lines = [
        "# SCAR — Full Report\n",
        f"**Run ID:** {data.run_id}",
        f"**Target:** {data.target}",
        f"**Mode:** {data.mode}",
        f"**Provider:** {data.provider}",
        f"**Date:** {data.timestamp}",
        f"**Total Findings:** {data.total}",
        f"**LLM Cost:** ${data.cost_usd:.4f}",
        f"**Coverage Gaps:** {len(data.degradations)}\n",
    ]

    # Summary counts
    lines.append("## Summary\n")
    lines.append("| Priority | Count | Severity | Count |")
    lines.append("|----------|------:|----------|------:|")
    lines.append(f"| URGENT | {data.urgent} | Critical | {data.critical} |")
    lines.append(f"| ELEVATED | {data.elevated} | Medium | {data.medium} |")
    lines.append(f"| MODERATE | {data.moderate} | Low | {data.low_severity} |")
    lines.append(f"| LOW | {data.low} | | |")

    if data.has_triage:
        lines.append(f"\nTriage: {data.triage_confirmed} confirmed, "
                      f"{data.triage_false_positive} false positive, "
                      f"{data.triage_needs_context} needs context")

    lines.extend(render_degradations_md(data.degradations))

    # Group findings by band
    # Filter by score — FPs have priority=0, naturally excluded from non-LOW bands
    groups = {"URGENT": [], "ELEVATED": [], "MODERATE": [], "LOW": []}
    for f in data.findings:
        groups.setdefault(f.priority_band, []).append(f)

    for band in ["URGENT", "ELEVATED", "MODERATE", "LOW"]:
        findings = groups.get(band, [])
        if not findings:
            continue

        lines.append(f"\n## {band} ({len(findings)} findings)\n")
        lines.append("| # | Score | Severity | Status | File | Line | CWE | Confidence | Finding |")
        lines.append("|---|-------|----------|--------|------|------|-----|------------|---------|")

        for i, f in enumerate(findings, 1):
            cwe = f.cwe or "-"
            conf = f"{f.confidence:.0%} ({f.confidence_label})"
            status = triage_status(f.triage_verdict)
            msg = f.message[:100]
            lines.append(
                f"| {i} | {f.priority:.2f} | {f.severity} | {status} | "
                f"{f.file_path} | {f.line} | {cwe} | {conf} | {msg} |"
            )

    # CWE breakdown
    if data.top_cwes:
        lines.append("\n## CWE Distribution\n")
        lines.append("| CWE | Count |")
        lines.append("|-----|------:|")
        for cwe, count in data.top_cwes:
            lines.append(f"| {cwe} | {count} |")

    lines.append("\n---")
    lines.append(f"*Generated by SCAR v{__version__}*")
    lines.append("*Priority = Severity x Confidence x Exposure*\n")
    return "\n".join(lines)
