"""Summary report renderer — one-page markdown overview.

Shows: metadata, priority band counts, severity counts, triage stats,
CWE breakdown, top 20 findings by priority.
"""
from __future__ import annotations

from security_review.reporting.common import ReportData, triage_status


def render_summary(data: ReportData) -> str:
    """Render a one-page markdown summary."""
    lines = [
        "# SCAR Report\n",
        f"**Run ID:** {data.run_id}",
        f"**Target:** {data.target}",
        f"**Mode:** {data.mode}",
        f"**Date:** {data.timestamp}",
        f"**Total Findings:** {data.total}",
        f"**LLM Cost:** ${data.cost_usd:.4f}\n",
    ]

    # Partial-failure banner — this report may be incomplete.
    if data.errors:
        lines.append(
            f"> ⚠ **PARTIAL RESULTS — {len(data.errors)} pass(es) failed.** "
            "Findings below reflect only the passes that completed."
        )
        lines.append("\n## Pass Failures\n")
        for err in data.errors:
            lines.append(f"- {err}")

    # Priority bands
    lines.append("## Priority\n")
    for band, count in [("URGENT", data.urgent), ("ELEVATED", data.elevated),
                        ("MODERATE", data.moderate), ("LOW", data.low)]:
        if count > 0:
            lines.append(f"- **{band}:** {count}")

    # Severity
    lines.append("\n## Severity\n")
    for label, count in [("Critical", data.critical), ("Medium", data.medium),
                         ("Low", data.low_severity)]:
        if count > 0:
            lines.append(f"- **{label}:** {count}")

    # Triage
    if data.has_triage:
        lines.append("\n## Triage\n")
        lines.append(f"- Confirmed: {data.triage_confirmed}")
        lines.append(f"- False Positive: {data.triage_false_positive}")
        lines.append(f"- Needs Context: {data.triage_needs_context}")

    # CWEs
    if data.top_cwes:
        lines.append("\n## Top CWEs\n")
        for cwe, count in data.top_cwes:
            lines.append(f"- {cwe}: {count}")

    # Top findings — filter by score (FPs have priority=0, naturally excluded)
    actionable = [f for f in data.findings if f.priority >= 0.20]
    if not actionable:
        actionable = [f for f in data.findings if f.priority > 0][:20]
    if actionable:
        lines.append("\n## Top Findings\n")
        lines.append("| Priority | Score | Severity | Status | File | Line | Finding |")
        lines.append("|----------|-------|----------|--------|------|------|---------|")
        for f in actionable[:20]:
            short_file = f.file_path.split("/")[-1] if "/" in f.file_path else f.file_path
            msg = f.message[:80]
            status = triage_status(f.triage_verdict)
            lines.append(
                f"| {f.priority_band} | {f.priority:.2f} | {f.severity} | "
                f"{status} | {short_file} | {f.line} | {msg} |"
            )

    lines.append("\n---")
    lines.append("*Generated by SCAR v1.0.0*")
    lines.append("*Priority: URGENT (>=0.70) | ELEVATED (>=0.40) | MODERATE (>=0.20) | LOW (<0.20)*\n")
    return "\n".join(lines)
