# Bandit B-code to CWE mapping
# Source: https://bandit.readthedocs.io/en/latest/plugins/

B101: {cwe: "703", name: "assert_used"}
B102: {cwe: "78", name: "exec_used"}
B103: {cwe: "276", name: "set_bad_file_permissions"}
B104: {cwe: "668", name: "hardcoded_bind_all_interfaces"}
B105: {cwe: "798", name: "hardcoded_password_string"}
B106: {cwe: "798", name: "hardcoded_password_funcarg"}
B107: {cwe: "798", name: "hardcoded_password_default"}
B108: {cwe: "377", name: "hardcoded_tmp_directory"}
B110: {cwe: "693", name: "try_except_pass"}
B112: {cwe: "693", name: "try_except_continue"}
B201: {cwe: "502", name: "flask_debug_true"}
B301: {cwe: "502", name: "pickle"}
B302: {cwe: "502", name: "marshal"}
B303: {cwe: "327", name: "md5_sha1"}
B304: {cwe: "327", name: "des"}
B305: {cwe: "327", name: "cipher_modes"}
B306: {cwe: "377", name: "mktemp_q"}
B307: {cwe: "94", name: "eval"}
B308: {cwe: "94", name: "mark_safe"}
B309: {cwe: "319", name: "httpsconnection"}
B310: {cwe: "22", name: "urllib_urlopen"}
B311: {cwe: "330", name: "random"}
B312: {cwe: "295", name: "telnetlib"}
B313: {cwe: "611", name: "xml_bad_cElementTree"}
B314: {cwe: "611", name: "xml_bad_ElementTree"}
B315: {cwe: "611", name: "xml_bad_expat"}
B316: {cwe: "611", name: "xml_bad_minidom"}
B317: {cwe: "611", name: "xml_bad_pulldom"}
B318: {cwe: "611", name: "xml_bad_sax"}
B319: {cwe: "611", name: "xml_bad_etree"}
B320: {cwe: "611", name: "xml_bad_lxml"}
B321: {cwe: "319", name: "ftp_related"}
B322: {cwe: "94", name: "input"}
B323: {cwe: "295", name: "unverified_context"}
B324: {cwe: "327", name: "hashlib_new_insecure_functions"}
B501: {cwe: "295", name: "request_with_no_cert_validation"}
B502: {cwe: "295", name: "ssl_with_bad_version"}
B503: {cwe: "295", name: "ssl_with_bad_defaults"}
B504: {cwe: "295", name: "ssl_with_no_version"}
B505: {cwe: "326", name: "weak_cryptographic_key"}
B506: {cwe: "94", name: "yaml_load"}
B507: {cwe: "295", name: "ssh_no_host_key_verification"}
B601: {cwe: "78", name: "paramiko_calls"}
B602: {cwe: "78", name: "subprocess_popen_with_shell_equals_true"}
B603: {cwe: "78", name: "subprocess_without_shell_equals_true"}
B604: {cwe: "78", name: "any_other_function_with_shell_equals_true"}
B605: {cwe: "78", name: "start_process_with_a_shell"}
B606: {cwe: "78", name: "start_process_with_no_shell"}
B607: {cwe: "78", name: "start_process_with_partial_path"}
B608: {cwe: "89", name: "hardcoded_sql_expressions"}
B609: {cwe: "78", name: "linux_commands_wildcard_injection"}
B610: {cwe: "78", name: "django_extra_used"}
B611: {cwe: "89", name: "django_rawsql_used"}
B701: {cwe: "94", name: "jinja2_autoescape_false"}
B702: {cwe: "79", name: "use_of_mako_templates"}
B703: {cwe: "94", name: "django_mark_safe"}
